@startuml

title __LAB7's Class Diagram__\n

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.client {
      class AuthorizeHelper {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.client {
      class Client {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.client {
      class CommandReader {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.Utils {
      class Constants {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.server {
      class FileLoader {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.json {
      class JSONArray {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.json {
      class JSONBoolean {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.json {
      class JSONEntity {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.json {
      class JSONNumber {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.json {
      class JSONObject {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.server {
      class JSONParse {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.json {
      class JSONParseException {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.json {
      class JSONParser {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.json {
      class JSONString {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.json {
      enum JSONType {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    class Message {
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.transmitter {
      class Receiver {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.transmitter {
      interface ReceiverListener {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.server {
      class RegisterHelper {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.server {
      class Resolver {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.client {
      class Room {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.server {
      class RoomDatabaseInteractor {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.client {
      class RoomFactory {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.transmitter {
      class Sender {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.transmitter {
      class SenderAdapter {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.transmitter {
      interface SenderListener {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.server {
      class Server {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.server {
      class ServerConfig {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.Utils {
      class StringEntity {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.server {
      class UsersDatabaseInteractor {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    class Utilities {
    }
  }
  

  CommandReader o-- Receiver : receiver
  JSONArray -up-|> JSONEntity
  JSONBoolean -up-|> JSONEntity
  JSONEntity -up-|> Serializable
  JSONEntity o-- JSONType : type
  JSONNumber -up-|> JSONEntity
  JSONObject -up-|> JSONEntity
  JSONString -up-|> JSONEntity
  Message -up-|> Serializable
  Receiver o-- ReceiverListener : listener
  Resolver -up-|> Runnable
  Resolver o-- Message : message
  Room -up-|> Comparable
  Room -up-|> Serializable
  Room o-- Shelf : shelf
  SenderAdapter -up-|> SenderListener
  StringEntity -up-|> Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
