@startuml

title __UTILS's Class Diagram__\n

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.Utils {
      class Constants {
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.Utils {
      class ANSI_COLORS {
          {static} + RESET : String
          {static} + BLACK : String
          {static} + RED : String
          {static} + GREEN : String
          {static} + YELLOW : String
          {static} + BLUE : String
          {static} + PURPLE : String
          {static} + CYAN : String
          {static} + WHITE : String
          {static} + BRIGHT_BLACK : String
          {static} + BRIGHT_RED : String
          {static} + BRIGHT_GREEN : String
          {static} + BRIGHT_YELLOW : String
          {static} + BRIGHT_BLUE : String
          {static} + BRIGHT_PURPLE : String
          {static} + BRIGHT_CYAN : String
          {static} + BRIGHT_WHITE : String
          {static} + BG_BLACK : String
          {static} + BG_RED : String
          {static} + BG_GREEN : String
          {static} + BG_YELLOW : String
          {static} + BG_BLUE : String
          {static} + BG_PURPLE : String
          {static} + BG_CYAN : String
          {static} + BG_WHITE : String
          {static} + BRIGHT_BG_BLACK : String
          {static} + BRIGHT_BG_RED : String
          {static} + BRIGHT_BG_GREEN : String
          {static} + BRIGHT_BG_YELLOW : String
          {static} + BRIGHT_BG_BLUE : String
          {static} + BRIGHT_BG_PURPLE : String
          {static} + BRIGHT_BG_CYAN : String
          {static} + BRIGHT_BG_WHITE : String
      }
    }
  }
  

  package ifmo.programming.lab7 {
    package ifmo.programming.lab7.Utils {
      class StringEntity {
          - string : String
          - arguments : String[]
          + getString()
          + setString()
          + getArguments()
          + setArguments()
          + set()
          + set()
      }
    }
  }
  

  Constants +-down- ANSI_COLORS
  StringEntity -up-|> Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
